import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['"DM Sans"', 'sans-serif'],
        heading: ['"Sora"', 'sans-serif'],
        label: ['"DM Sans"', 'sans-serif'],
        body: ['"DM Sans"', 'sans-serif'],
        h1: ['"Sora"', 'sans-serif'],
        h2: ['"Sora"', 'sans-serif'],
        h3: ['"Sora"', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#faf8ff",
        foreground: "hsl(var(--foreground))",
        "surface": "#faf8ff",
        "on-surface-variant": "#434655",
        "surface-tint": "#0053db",
        "primary-container": "#2563eb",
        "surface-variant": "#e1e2ed",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface": "#191b23",
        "on-error": "#ffffff",
        "secondary-container": "#d5e0f8",
        "tertiary-container": "#bc4800",
        "primary-fixed": "#dbe1ff",
        "surface-container": "#ededf9",
        "on-background": "#191b23",
        "on-error-container": "#93000a",
        "surface-container-high": "#e7e7f3",
        "outline-variant": "#c3c6d7",
        "on-secondary-fixed-variant": "#3c475a",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb596",
        "on-primary-fixed": "#00174b",
        "inverse-surface": "#2e3039",
        "on-secondary-container": "#586377",
        "surface-bright": "#faf8ff",
        "secondary-fixed": "#d8e3fb",
        "on-secondary-fixed": "#111c2d",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdbcd",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-on-surface": "#f0f0fb",
        "error": "#ba1a1a",
        "surface-container-low": "#f3f3fe",
        "on-primary-container": "#eeefff",
        "on-primary": "#ffffff",
        "surface-dim": "#d9d9e5",
        "inverse-primary": "#b4c5ff",
        "surface-container-highest": "#e1e2ed",
        "on-tertiary-fixed": "#360f00",
        "outline": "#737686",
        "tertiary": "#943700",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-tertiary-container": "#ffede6",
        "secondary-fixed-dim": "#bcc7de",
        brand: {
          light: '#2563eb',
          DEFAULT: '#004ac6',
          dark: '#191b23',
        },
        soft: {
          blue: '#faf8ff',
          purple: '#f5f3ff',
        },
        primary: {
          DEFAULT: "#2563EB",
          hover: "#003ea8",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
